# Generated by Django 5.2.11 on 2026-02-25 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit', models.PositiveSmallIntegerField()),
                ('confidence', models.FloatField()),
                ('source', models.CharField(choices=[('file', 'File Upload'), ('canvas', 'Canvas/Base64')], max_length=16)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'digit_predictions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('advanced', 'Advanced CNN'), ('simple', 'Simple CNN')], max_length=32)),
                ('epochs', models.PositiveIntegerField()),
                ('batch_size', models.PositiveIntegerField()),
                ('test_accuracy', models.FloatField()),
                ('test_loss', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'digit_training_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionProbability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digit_class', models.PositiveSmallIntegerField()),
                ('probability', models.FloatField()),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probabilities', to='digit_api.prediction')),
            ],
            options={
                'db_table': 'digit_prediction_probabilities',
                'unique_together': {('prediction', 'digit_class')},
            },
        ),
    ]
